#!/usr/bin/env python3
"""Positive controls for apps/web/src/typeScaleUnits.test.ts.

Every control is a ONE-EDIT mutation of the PRODUCT (preset.ts or theme.css) plus a NAMED
PREDICTION of which test case must red and which must stay green. The verdict is read from the
set of failing test NAMES, never from an exit code:

  · an exit code cannot tell a caught mutation from a file that no longer parses;
  · a control that reds three cases when it was predicted to red one has not been understood,
    even though "CAUGHT" would print either way.

So each row carries BOTH halves — `reds` (must fail) and everything else (must stay green) — and
a control scores CAUGHT only when the failing set is EXACTLY the predicted set. Two rows are
predicted NOT CAUGHT on purpose: a guard that reds on every edit to preset.ts is a guard that
gets deleted at the next merge, so proving it distinguishes a unit change from a leading change
is part of the campaign, not politeness.

Anchors are asserted to appear EXACTLY ONCE before any write, and the tree is restored in a
`finally` with a closing sha256 check — a crash between mutate and restore must not leave a
mutated scale on disk.

Usage:  python3 scripts/w11-type-scale-controls.py
"""
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WEB = REPO / "apps/web"
PRESET = REPO / "packages/ui/src/preset.ts"
THEME = REPO / "packages/ui/src/theme.css"
TEST = "src/typeScaleUnits.test.ts"

# The six console-step cases are generated by it.each; vitest names them with the step spelled in.
STEP = "`{}` is declared in rem and still resolves to its old px at a 16px root"
BASE = "the base every unclassed element inherits is root-relative too"
MARKETING = "the marketing steps are still px-anchored, and this is the measurement to redo"
FLOOR = "every step in the scale is on exactly one of the two tables"
JSDOM = "jsdom cannot tell these apart, which is why this file reads declarations"

CONTROLS = [
    {
        "id": "C1",
        "what": "the `body` step goes back to px — the step by count the product is written in",
        "file": PRESET,
        "find": "body: ['0.875rem', { lineHeight: '1.45', fontWeight: '400' }], // 14px",
        "repl": "body: ['14px', { lineHeight: '1.45', fontWeight: '400' }],",
        "reds": [STEP.format("body")],
        "expect": "the unit assertion for `body`",
    },
    {
        "id": "C2",
        "what": "theme.css's base goes back to px — the six steps stay rem, the FLOOR does not",
        "file": THEME,
        "find": "  font-size: 0.875rem;",
        "repl": "  font-size: 14px;",
        "reds": [BASE],
        "expect": "the base assertion; NOT any per-step case, which is the point of a separate case",
    },
    {
        "id": "C3",
        "what": "`title` is rem but the WRONG rem — the unit is right and the size moved",
        "file": PRESET,
        "find": "title: ['1.5rem', { lineHeight: '1.2', fontWeight: '640' }], // 24px at a 16px root",
        "repl": "title: ['1.6rem', { lineHeight: '1.2', fontWeight: '640' }], // 24px at a 16px root",
        "reds": [STEP.format("title")],
        "expect": "the SIZE half of the title case — a unit-only guard would pass this",
    },
    {
        "id": "C4",
        "what": "a SEVENTH step appears, classified by nobody",
        "file": PRESET,
        "find": "      fontSize: {",
        "repl": "      fontSize: {\n        subhead: ['1rem', { lineHeight: '1.3', fontWeight: '600' }],",
        "reds": [FLOOR],
        "expect": "the classification floor ALONE — no per-step case names `subhead`, which is "
                  "exactly why the floor exists",
    },
    {
        "id": "C5",
        "what": "a MARKETING step is converted on the way past, without the 320x24 re-measurement",
        "file": PRESET,
        "find": "figure: ['28px', { lineHeight: '1', fontWeight: '560' }],",
        "repl": "figure: ['1.75rem', { lineHeight: '1', fontWeight: '560' }],",
        "reds": [MARKETING],
        "expect": "the px-anchor case, whose message carries the number to re-measure",
    },
    {
        "id": "C6",
        "what": "`eyebrow` is relative — but to the PARENT, not the root",
        "file": PRESET,
        "find": "eyebrow: ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.24em', fontWeight: '400' }], // 11px",
        "repl": "eyebrow: ['0.6875em', { lineHeight: '1.2', letterSpacing: '0.24em', fontWeight: '400' }], // 11px",
        "reds": [STEP.format("eyebrow")],
        "expect": "the unit assertion — em compounds through nesting and is not the reader's size",
    },
    {
        "id": "C7",
        "what": "a LEADING changes and nothing else — predicted NOT CAUGHT, deliberately",
        "file": PRESET,
        "find": "body: ['0.875rem', { lineHeight: '1.45', fontWeight: '400' }], // 14px",
        "repl": "body: ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }], // 14px",
        "reds": [],
        "expect": "NOTHING. This file is a rule about UNITS. A guard that reds on every preset "
                  "edit is a guard someone deletes.",
    },
    {
        "id": "C8",
        "what": "an unclassified step appears in the MIDDLE of the block, not at the top",
        "file": PRESET,
        "find": "        'display-1': [",
        "repl": "        'display-0-unused-order-probe': ['28px', { lineHeight: '1', fontWeight: '560' }],\n        'display-1': [",
        "reds": [FLOOR],
        "expect": "the floor again, from the OTHER direction — a step added anywhere in the block, "
                  "not only at the top, is unclassified",
    },
]


def run_guard() -> dict:
    """Run ONLY the guard file and return {test name: [messages]} for the failures."""
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as fh:
        report = Path(fh.name)
    try:
        subprocess.run(
            ["npx", "vitest", "run", TEST, "--reporter=json", f"--outputFile={report}"],
            cwd=WEB, capture_output=True, text=True, timeout=600,
        )
        try:
            data = json.loads(report.read_text())
        except Exception:
            return {"__COLLECTION_ERROR__": ["the guard file did not run at all"]}
        failed, total = {}, 0
        for tr in data.get("testResults", []):
            for ar in tr.get("assertionResults", []):
                total += 1
                if ar.get("status") == "failed":
                    failed[ar.get("title", "")] = ar.get("failureMessages", [])
        if total == 0:
            return {"__NO_TESTS_RAN__": ["the guard file produced no assertions"]}
        return failed
    finally:
        report.unlink(missing_ok=True)


def main() -> int:
    sha_before = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in (PRESET, THEME)}
    backups = {p: p.read_text() for p in (PRESET, THEME)}

    print("BASELINE (no mutation) — every case must be green, or every verdict below is noise")
    base_failures = run_guard()
    if base_failures:
        print(f"  FAIL: the guard is not green before the campaign: {list(base_failures)}")
        return 2
    print("  ok\n")

    results = []
    try:
        for c in CONTROLS:
            path, find = c["file"], c["find"]
            text = backups[path]
            # A control must prove its own premise before it writes anything.
            n = text.count(find)
            if n != 1:
                print(f"{c['id']}  ANCHOR NOT UNIQUE ({n} matches) — control not run: {find[:60]!r}")
                results.append((c, "ANCHOR", set(), set()))
                continue
            mutated = text.replace(find, c["repl"])
            assert mutated != text, f"{c['id']} rewrote nothing"
            path.write_text(mutated)
            got = run_guard()
            path.write_text(text)

            predicted = set(c["reds"])
            actual = set(got)
            if predicted == actual:
                verdict = "CAUGHT" if predicted else "NOT CAUGHT (as predicted)"
            else:
                verdict = "MISPREDICTED"
            results.append((c, verdict, predicted, actual))
            print(f"{c['id']}  {verdict}")
            print(f"    mutation : {c['what']}")
            print(f"    predicted: {c['expect']}")
            for name in sorted(actual):
                msg = (got[name][0] if got[name] else "").strip().splitlines()
                first = next((ln for ln in msg if ln.strip()), "")
                print(f"    reddened : {name}")
                print(f"               {first[:150]}")
            if verdict == "MISPREDICTED":
                print(f"    expected reds: {sorted(predicted)}")
            print()
    finally:
        for p, t in backups.items():
            p.write_text(t)
        sha_after = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in (PRESET, THEME)}
        assert sha_after == sha_before, f"RESTORE FAILED: {sha_after} != {sha_before}"
        print("restored: sha256 of preset.ts and theme.css match the pre-campaign bytes")

    caught = sum(1 for _, v, _, _ in results if v.startswith("CAUGHT"))
    inert = sum(1 for _, v, _, _ in results if v.startswith("NOT CAUGHT"))
    bad = [c["id"] for c, v, _, _ in results if v in ("MISPREDICTED", "ANCHOR")]
    print(f"\n{caught} caught by the predicted case, {inert} inert as predicted, "
          f"{len(bad)} mispredicted{': ' + ', '.join(bad) if bad else ''}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
